title: "On software"

name: "Nathan Boyd"

email: nathan@engineernathan.org

author:
  name: "Nathan Boyd"
  avatar: "/assets/img/wizard.png"
  bio: "your host"
  location: "Indianapolis"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nathanboyd"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nathan-boyd"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nathanboyd"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nathan-boyd"

description: > # this means to ignore newlines until "baseurl:"
  musings

baseurl: "/"
url: "http://blog.localdomain"

markdown: kramdown
theme: minimal-mistakes-jekyll

paginate: 5

include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-paginate

timezone: America/Indianapolis


sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

masthead_title: "On Software"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        nav: "docs"

search: true

search_full_content: true
