defaults: &defaults
  working_directory: ~/repo
version: 2.1
jobs:
  bundle:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: bundle install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ./
          paths:
            - Dockerfile
            - Gemfile
            - vendor
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
            - Dockerfile
            - Gemfile
            - vendor
  doctor:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: jekyll doctor
          command: bundle exec jekyll doctor
  test:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: HTMLProofer tests
          command: |
              bundle exec htmlproofer \
              --file-ignore './_site/404.html' \
              --allow-hash-href \
              --check-html \
              --disable-external \
              ./_site
  publish:
    <<: *defaults
    docker:
      - image: circleci/golang
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run: echo $DOCKER_PASSWORD | base64 --decode | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker build . -t "$DOCKER_REPO/$DOCKER_IMAGE:$CIRCLE_TAG"
      - run: docker push "$DOCKER_REPO/$DOCKER_IMAGE:$CIRCLE_TAG"
workflows:
  version: 2
  build-master:
    jobs:
      - bundle:
          filters:
            branches:
              only: master
      - doctor:
          requires:
            - bundle
          filters:
            branches:
              only: master
      - build:
          requires:
            - bundle
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
  publish:
    jobs:
      - bundle:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - doctor:
          requires:
            - bundle
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - bundle
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - build
            - doctor
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
